name: marriage_gate
description: "Enterprise-level matrimony mobile app with clean architecture"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # UI & Design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

  # Navigation
  go_router: ^15.1.2

  app_links: ^6.3.2

  # Networking & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  # Authentication
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2

  # Real-time Chat
  web_socket_channel: ^3.0.3

  # Push Notifications
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^19.3.0

  # Location & Maps
  geolocator: ^13.0.1
  google_maps_flutter: ^2.6.0

  # Media & Images
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  image_cropper: ^9.1.0

  # Deep Linking
  # uni_links: ^0.5.1

  # In-App Purchases
  in_app_purchase: ^3.1.13

  # Analytics & Monitoring
  firebase_analytics: ^11.3.3
  sentry_flutter: ^9.4.0

  # Utilities
  intl: ^0.19.0
  encrypt: ^5.0.3
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.2
  device_info_plus: ^11.3.0
  connectivity_plus: ^6.1.4
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.10
  riverpod_generator: ^2.4.0
  retrofit_generator: ^9.1.5
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/json/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: Sriracha
      fonts:
        - asset: assets/fonts/Sriracha-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
